### ISSUE TITLE
Triangular Lattice Heisenberg model

### ISSUE THREAD

**Issue by LinuxDaFaHao** [issp-center-dev/TeNeS#18]
It is a very nice package that can help to calculate the many-body systems. I tested the triangular lattice antiferromagnetism Heisenberg model for bond dimension D=2,3 but it didn't work well. The spin-spin correlations don't distribute evenly so the state doesn't like a Neel state. I'm not sure if I had some mistakes in operation or there is an intrinsic bias when mapping triangular lattices to square lattice tensor networks. 

In principle, we can get a precise PESS state for the triangular lattice model and map it to square lattice PEPS by contracting some indices. So the square lattice PEPS is an adequate ansatz for the triangular AFM Heisenberg model. 

I want to ask if you meet the same question when tested. if so, the square lattice PEPS full update may not a good scheme to optimize triangular ground states.

The version I used is [ver. 1.0-beta: 2020/03/30]. Two of the input/output files are attached (I renamed the filename suffixes). By the way, does increasing the bond dimension work?

[input.txt](https://github.com/issp-center-dev/TeNeS/files/4414598/input.txt)
[twosite_obs.txt](https://github.com/issp-center-dev/TeNeS/files/4414605/twosite_obs.txt)

**Comment by TsuyoshiOkubo** [comment]
Hi @LinuxDaFaHao . Thank you for your comment.We checked your input, and reproduced inhomogeneity of the spin-spin correlation function. 

After several tests in our implementation, we realized it is caused by the decomposition of "diagonal" interactions in the imaginary time evolution. In 1.0 beta, even if the interactions are homogeneous, further neighbor interactions might be decomposed inhomogeneously. Then, for finite bond dimensions, it causes inhomogenous spin-spin correlations. 

Recently, we released version 1.0 where we fixed this point. Thus, we believe it works better than before. 

As  you mentioned, I agree with that the square lattice PEPS can represent PESS for the triangular lattice models. Thus, in principle, it must work as well as PEPS. On the other hand, due to the optimization, in our case it is the imaginary time evolution, we might obtain different results. Unfortunately, our treatment of further neighbor interactions contains strong approximation than the standard treatment of the diagonal interaction, in order to treat general interactions. Thus, the result of TeNeS might not be as well as the standard PEPS and PESS calculation of the triangular lattice Heisenberg model. However, we believe it correctly converges to the ground state when we increase the bond dimension.

**Comment by LinuxDaFaHao** [comment]
Hi, Thanks for your reply. I push the bond dimension to 5 with bond dimension 50 or 80 and it still doesn't work well. It may be very subtle to tune the parameters. The version I used is 1.0-beta.

I just noticed that in the new documents, you omitted the explanation for the tensor network of the triangular lattice. I mean, does it still make use of the square tensor network?

**Comment by yomichi** [comment]
As @TsuyoshiOkubo says, we have added some improvements and fixes in v1.0.0 from v1.0-beta (Thank you for comments!). Please upgrade.

TeNeS still treats the square TN.
We should show the mapping from a physical lattice (e.g., triangular) to a square TN, but I'm sorry that I didn't.
For triangular with 3x3, one unit cell of a TN consists of the following sites,

```
6 7 8
3 4 5
0 1 2
```

and 1 and 3 sites are connected but 0 and 4 sites are not.

**Comment by HamidArianZad** [comment]
Hi,
I want to simulate the magnetization of a triangular lattice including two-body and three-body interactions that is in the presence of an external magnetic field H. Does the TeNeS support such a calculation?
The Hamiltonian of my favorite model is presented in attachment.
![Hamiltonian](https://user-images.githubusercontent.com/97589591/150701292-68f966f4-a143-465f-a3ab-3d74fc6e1eae.png)

**Comment by yomichi** [comment]
I'm sorry for not closing this issue (#18) which seems already solved.

@HamidArianZad 
Could you make a new issue for a new issue/question?
